#!/bin/bash -l
#PBS -N batch_MIMICS
#PBS -A P93300641
#PBS -l walltime=10:00:00
#PBS -q regular
#PBS -j oe
#PBS -m abe
#PBS -M valent@ucar.edu
#PBS -l select=1:ncpus=36:ompthreads=36

### Intialize the PBS environment

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Load modules required to run the job
date
module purge
module reset
module load R/4.1.2
module li

### Run program
Rscript hello_world.R

